### ISSUE TITLE
Warning: Use of undefined constant CALLERSANDBOX

### ISSUE THREAD

**Issue by nickweisser** [openstream/woocommerce-runmyaccounts#1]
Just installed version 1.1.0 of this plugin on WordPress 5.2.2 and WooCommerce 3.6.4. When I go to the settings page I see a warning 

`Warning: Use of undefined constant CALLERSANDBOX - assumed 'CALLERSANDBOX' (this will throw an Error in a future version of PHP) in /var/www/.../wp-content/plugins/woocommerce-runmyaccounts/classes/class.RmaApi.php on line 70 No connection. Please check your settings.
If the test mode is selected the test client is used and the test API key.`

![Run_My_Accounts_-_Settings_‹_Run_my_Accounts_—_WordPress](https://user-images.githubusercontent.com/58966/60160980-dacb0d00-97f6-11e9-8d2a-cd8710f32ec6.png)

Is this normal before entering any credentials? If so, the error handling should probably be more user friendly.

**Comment by codestylist** [comment]
RunMyAccounts changed the API url so the connection faild with the old one.
This issue is fixed with version 1.1.1.
